Vector mult n
muzny/csci3010-fall2018-collab pull request #5
Opened 2018-09-18 16:18 UTC by EricOropezaelwood

Check out this sick function.

2018-09-18 16:21 UTC, faisalmlalani approved these changes
It's pretty damn sick.

2018-09-18 16:22 UTC, kyleHilton95 requested changes
good

2018-09-18 16:22 UTC, JosiahGraham approved these changes
Cool?

2018-09-18 16:22 UTC, kyleHilton95 approved these changes

2018-09-19 20:15 UTC, muzny requested changes
Make sure to use function comments and follow our style guide.

We'll talk about adding tests on Thursday.

2018-09-19 20:15 UTC, muzny commented on math/FunMath.cpp
> +std::vector<int> Vect_Mult(std::vector<int> vect, int n){
- Add a function comment: what does it do, what are the parameters/return values
- Make sure to follow our style guide for functions NamedLikeThis

2018-09-19 20:15 UTC, muzny commented on math/FunMath.cpp
> +  for (unsigned i=0;i<vect.size();i++){
Why is i unsigned? add spaces to this for loop to make it more readable.

2018-09-30 22:11 UTC, muzny approved these changes

2026-03-02 16:41 UTC, closed without merging